import en from './en.json';
import es from './es.json';
/**
 * Locale catalogs owned by this package, keyed by language. `en.json` is the
 * source of truth; other locales are generated by `scripts/translate-messages.mjs`
 * and may be empty until that script is run (missing keys fall back to the
 * English `defaultMessage`).
 */
export const catalogs: Record<string, Record<string, string>> = { en, es };
